### ISSUE TITLE
eMMC isn't supported in ATF

### ISSUE THREAD

**Issue by hzhuang1** [ARM-software/tf-issues#376]
In a lot of embedded platform, eMMC device is the only one storage device. So supporting eMMC stack is necessary in ATF.

**Comment by vwadekar** [comment]
I am assuming that this driver would be necessary for lower level BLs - BL0/1/2. This seems like a worthy enhancement. Are you planning to add quirks similar to the linux driver? Quirks are a good way to allow platforms to override default behavior.

**Comment by hzhuang1** [comment]
Yes, I will append similar quirks. For example, I only support CMD18 and CMD12 for read operation. But CMD23 and CMD18 should also be supported.

**Comment by sbranden** [comment]
We have emmc fully functional in our non-upstreamed ATF version.  Lower level implementation is not clean.  I can contribute the io_emmc so we have compatible APIs?

**Comment by hzhuang1** [comment]
I think you can submit your io_emmc first. Then Dan could make a decision.

**Comment by sbranden** [comment]
Submission in github here:
https://github.com/sbranden/arm-trusted-firmware/tree/tf_issue_376

Please feel free to comment.

**Comment by danh-arm** [comment]
I had a brief look at both pull requests (https://github.com/ARM-software/arm-trusted-firmware/pull/558 and https://github.com/ARM-software/arm-trusted-firmware/pull/566). Haojian's one appears to have a better abstracted IO driver, in that it introduces a new block device type instead of creating a specific eMMC block driver and re-using the memmap device type.

Scott - do you think you could review this (https://github.com/ARM-software/arm-trusted-firmware/pull/558) to see if it meets your needs?

Regarding the low level implementation, we (ARM) are not experts in this field and don't have a particularly strong interest in this driver. We will review it for general code quality but we need the TF community's help to produce a strong implementation.

**Comment by sbranden** [comment]
I do not have the bandwidth to review such implementations in detail right now.  At first glance it will be adaptable or modifiable.   Our version works right now for our purposes.  I think we'll have to let Haojian do what he is doing and then fix/adapt as needed in the future.  It would be good if he could look at my commit to see what other features it has that are not already in his design.

**Comment by danh-arm** [comment]
Closing this. The generic driver support was merged in https://github.com/ARM-software/arm-trusted-firmware/pull/597. The specific designware driver is still outstanding due to IP issues (https://github.com/ARM-software/arm-trusted-firmware/pull/599)

**Comment by hzhuang1** [comment]
Reopen it.

**Comment by hzhuang1** [comment]
Close since the fix is merged.
