### ISSUE TITLE
Running position independent support for arm trusted firmware ?

### ISSUE THREAD

**Issue by prime-zeng** [ARM-software/tf-issues#416]
Since arm trusted firmware can be executed only in the fix position once it has been compiled, but we may need to a single image to run on different boards with different memory size and the memory layout is different for arm trusted firmware. 

Any plan to support or any suggestion of how to do it?

**Comment by vwadekar** [comment]
I remember discussing this in the past, but the idea did not fly. I suppose
ARM did not have any plans then.

Would like to know if the stand has changed.

Thanks.

**Comment by danh-arm** [comment]
This is a duplicate of the issue here: https://github.com/ARM-software/tf-issues/issues/111. There is still no plan from our side to implement this but we can raise the priority if there is enough demand. Please contact us privately if you wish to discuss our roadmap.

In terms of how to do it, that is not a simple question. It requires some serious design thinking and discussion.

**Comment by prime-zeng** [comment]
@danh-arm So how to contact with you?  I think this request is a common requirement for real product.

**Comment by danh-arm** [comment]
> So how to contact with you?
Initially you should contact your ARM partner manager or ARM support.

**Comment by prime-zeng** [comment]
OK, got it, thinks.
