### ISSUE TITLE
Question about aarch32 tf in sp_min and spd

### ISSUE THREAD

**Issue by acy54321** [ARM-software/tf-issues#439]
Hi I have some question about AARCH32_SP is the AArch32 EL3 Runtime Software and it corresponds to the BL32 image provided PSCI Library as Runtime Software, in the doc say "Software may include other runtime services, for example Trusted OS services" as I know OPTEE SPD is a Trusted OS dispatch services. But now in makefile have $(error "Error: SPD is incompatible with AArch32.") that let AArch32 can't use OPTEE SPD as a Runtime services, I would like to ask whether there is a problem in my perception?? And in feature AARCH32_SP whether it can support SPD as a runtime services ??

**Comment by danh-arm** [comment]
Hi @acy54321 

The term SPD (Secure Payload Dispatcher) is only meaningful in the AArch64 case, where an SPD integrated into BL31 communicates with the SP (Secure Payload), BL32.

In AArch32, the expectatation is that all runtime secure world functionality is tightly integrated into the SP (or BL32) image. This is includes the secure monitor, the PSCI implementation and any Trusted OS services.

The upstream SP_MIN demonstrates integration of a minimal secure monitor + PSCI implementation, but this does not provide any other runtime services, and does not communicate with an SPD.

The plan is for AArch32 OP-TEE to eventually integrate the Trusted Firmware PSCI library so that it can take advantage of the standardized PSCI implementation, while also providing its own Trusted OS services. There would be no need for an OP-TEE SPD. That work has not been done yet.

Regards

Dan.
