### ISSUE TITLE
PSCI: Add support for CPU_OFF capabilities for remote / non-self cores

### ISSUE THREAD

**Issue by ddriscoll3711** [ARM-software/tf-issues#443]
There are scenarios in AMP configurations that utilize a master-slave configuration (ie remoteproc) that require support for the master to shutdown a remote core.

This is different than the SMP scenario where the core shuts itself down once the OS has migrated all threads / interrupts to other CPUs.

This could be a new PSCI interface or modification of existing CPU_OFF interface to include a target CPU parameter.

My apologies if this functionality is possible via other PSCI services though I didn't see such capabilities in the PSCI 1.0 specification.

**Comment by soby-mathew** [comment]
@ddriscoll3711, currently PSCI only allows to cores to turn itself OFF. AFAICS, allowing other cores to turn of target CPUs would be complicated because of the nature of per CPU data and hardware components which can only be accessed by the target CPU (like GIC cpu interface) and I don't see PSCI ever adding support for this.

Is it not possible for a service running on the remote slave core to receive an `OFF` command from the master and invoke PSCI_CPU_OFF on itself?
