### ISSUE TITLE
PSCI: psci_cpu_on_start execution failure

### ISSUE THREAD

**Issue by orenbh** [ARM-software/tf-issues#451]
Hi,

psci_cpu_on_start calls platform specific code to power up target cpu, in case of success it will execute cm_init_context_by_index which will be used by target cpu during power up.

I'm facing a problem where target cpu has powered up and started execution before cm_init_context_by_index ended successfully by the cpu executing the psci_cpu_on_start.

I'm running stability test, which periodically power down / up cpu's 1,2,3, the problem appears after many test cycles,  it can execute more than 30000 cycles on each core before it fails to come up.

my question is why cm_init_context_by_index initialize context after the cpu has been power up in platform specific pwr_domain_on?

Thanks
Oren

**Comment by soby-mathew** [comment]
Hi @orenbh, 

> psci_cpu_on_start calls platform specific code to power up target cpu, in case of success it will execute cm_init_context_by_index which will be used by target cpu during power up.
I'm facing a problem where target cpu has powered up and started execution before cm_init_context_by_index ended successfully by the cpu executing the psci_cpu_on_start.

Yes, this is a likely scenario which is anticipated in the implementation. This is handled by using a per-cpu spinlock which is [acquired](https://github.com/ARM-software/arm-trusted-firmware/blob/master/lib/psci/psci_on.c#L86) by the caller of PSCI CPU ON and the target CPU [waits](https://github.com/ARM-software/arm-trusted-firmware/blob/master/lib/psci/psci_on.c#L186) for this spinlock to be released before using the context. The spinlock ensures that the `cm_init_context_by_index` for target CPU has completed before it is utilized by the target psci_cpu_on_finish handler.

> my question is why cm_init_context_by_index initialize context after the cpu has been power up in platform specific pwr_domain_on

This is because the platform `pwr_domain_on` handler can return failure and target context will only be initialized and overwritten if the handler succeeds. The spinlock I mentioned above ensures synchronization and I would expect that it is enough to ensure the sequence.

> I'm running stability test, which periodically power down / up cpu's 1,2,3, the problem appears after many test cycles, it can execute more than 30000 cycles on each core before it fails to come up.

I doubt that context initialization sequence is to blame for the failure. Please note that the invocation of platform [`pwr_domain_on`](https://github.com/ARM-software/arm-trusted-firmware/blob/master/lib/psci/psci_on.c#L135) and [`pwr_domain_on_finish`](https://github.com/ARM-software/arm-trusted-firmware/blob/master/lib/psci/psci_on.c#L166) are not synchronized by the generic code because it is expected that the  `pwr_domain_on_finish` can only execute on the target after `pwr_domain_on` has powered it ON. So if your implementation of the platform hooks has some shared data or some sequence dependency between them, you have to ensure sync/sequence in the hooks.
