### ISSUE TITLE
What is the proper way to pass secure memory map region to BL33?

### ISSUE THREAD

**Issue by Mathieu-Brcm** [ARM-software/tf-issues#477]
Hi ATF team,

In the case where BL31 is running from DRAM, a secure region would be allocated in DRAM for it.
BL33 (non-secure) would need to know about that area so it does not try to allocate/claim this region as available.

Is there a standard way to pass that information to BL33?

Thanks for any pointers,
-Mathieu

**Comment by danh-arm** [comment]
Hi Mathieu

Sorry, there isn't a standard way to do this currently (as far as I know). Some possible options are:

1. BL33 just statically defines the DRAM to use (minus the secure region).

2. BL33 parses a config file to define the DRAM to use, possibly even sharing this with ARM TF. For some platforms, that config file could be a device tree.

3. The DRAM regions to use are passed in a platform specific structure in a register during BL33 hand-off.

4. The platform provides an SMC interface for BL33 to enquire the available memory regions (other than the one that BL33 is already running in!). Some previous efforts were made to standardize an interface to do this and also allow dynamic changes to the available regions. Unfortunately these efforts stalled since it proved hard to do implement something that would work across many platforms.

Regards

Dan.
