### ISSUE TITLE
suspend finish flow

### ISSUE THREAD

**Issue by igalil86** [ARM-software/tf-issues#537]
During suspend finish flow, in psci_do_pwrup_cache_maintenance function (lib/psci/aarch64/psci_helpers.S) we execute the following code:
                /* ---------------------------------------------
                * Calculate and store the size of the used
                * stack memory in x1. Calculate and store the
                * stack base address in x0.
                * ---------------------------------------------
                */
                bl            plat_get_my_stack
                mov       x1, sp
                sub         x1, x0, x1
                mov       x0, sp
                bl            inv_dcache_range

Can you please explain why we need to invalidate the CPU stack at this point?

Thanks,
Igal

**Comment by geesun** [comment]
The reason is the cpu use the stack before it turn on the caches.

Here is the explain: 

1. Normal memory can be speculatively accessed by the processor and this means that it can potentially automatically load data into the cache. 

2. In a SMP systems, eventhough the stack is per-cpu, due to cache speculation , other CPUs may pull in lines corresponding to stack of current CPU. 

3. When we turn on cache on current CPU, there is a chance that we will hit stale cache lines which was fetched earlier by other CPU.

4. To be safe, invalidate all the cache lines corresponding to the used stack for this CPU.
