### ISSUE TITLE
Question about `console_getc()`

### ISSUE THREAD

**Issue by antonio-nino-diaz-arm** [ARM-software/tf-issues#586]
@jwerner-chromium 

Is there any reason why the current implementation of `console_getc()` is blocking in the multi console driver? The old driver one wasn't blocking, and it isn't used anywhere in the upstream code, so we were thinking about just returning after the first iteration of the console linked list. It would be helpful to implement a `getc()` with a timeout, which can't be done with the current driver.

**Comment by jwerner-chromium** [comment]
The old drivers were blocking (e.g. see here: https://github.com/ARM-software/arm-trusted-firmware/blob/82cb2c1ad9897473743f08437d0a3995bed561b9/drivers/arm/pl011/aarch64/pl011_console.S#L123 ), so I tried to maintain that behavior. The difference is that previously every individual driver was implementing the loop to wait for content itself. With multiple consoles we cannot have that, because the reasonable behavior you'd expect is to get a char as soon as any of the registered consoles has one available. So I made the individual driver implementations non-blocking and moved the loop into the framework's console_getc().

I don't particularly care about either behavior, so if Arm is okay with changing the behavior to non-blocking then go for it. I just didn't want to change the high-level behavior myself because I wanted the API change to be transparent to platforms (including out-of-tree). I agree that in general a non-blocking implementation is more useful (and the blocking behavior could easily be implemented with another small wrapper on top of that).
